# Generated by Django 5.2.1 on 2025-05-28 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bus', models.IntegerField(default=0)),
                ('modelo', models.CharField(max_length=150)),
                ('capacidad', models.IntegerField(default=0)),
                ('gps', models.BooleanField(verbose_name=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programas_Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorrido_actualizado', models.CharField(max_length=150)),
                ('tiempo_actualizado', models.CharField(max_length=150)),
                ('vias_acceso', models.CharField(max_length=150)),
                ('horarios', models.TimeField()),
                ('afluencia_personas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Puntos_Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_discapacidad', models.BooleanField(verbose_name=True)),
                ('inclusion_extranjeros', models.BooleanField(verbose_name=True)),
                ('formas_pago', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Portales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150)),
                ('buses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.buses')),
                ('programas_rutas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.programas_rutas')),
                ('puntos_recarga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.puntos_recarga')),
            ],
        ),
    ]
