# Generated by Django 5.2.1 on 2025-05-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas_rutas',
            name='horarios',
        ),
    ]
