# Generated by Django 5.2.1 on 2025-05-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portales', '0002_remove_programas_rutas_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paraderos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_discapacidad', models.BooleanField(default=False)),
                ('punto_asignado', models.CharField(max_length=150)),
                ('capacidad_total_buses', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='portales',
            name='puntos_recarga',
        ),
        migrations.RemoveField(
            model_name='portales',
            name='buses',
        ),
        migrations.RemoveField(
            model_name='portales',
            name='programas_rutas',
        ),
        migrations.AddField(
            model_name='programas_rutas',
            name='horario_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='programas_rutas',
            name='horario_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='programas_rutas',
            name='portal_final',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutas_como_destino', to='Portales.portales'),
        ),
        migrations.AddField(
            model_name='programas_rutas',
            name='portal_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutas_como_origen', to='Portales.portales'),
        ),
        migrations.AlterField(
            model_name='buses',
            name='gps',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Puntos_Recargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_discapacidad', models.BooleanField(default=False)),
                ('inclusion_extranjeros', models.BooleanField(default=False)),
                ('formas_pago', models.CharField(max_length=150)),
                ('portales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.portales')),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('zona_asignada', models.CharField(max_length=150)),
                ('horario_inicio', models.DateTimeField(null=True)),
                ('horario_fin', models.DateTimeField(null=True)),
                ('buses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.buses')),
                ('programas_Rutas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.programas_rutas')),
            ],
        ),
        migrations.CreateModel(
            name='Rutas_Paraderos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.buses')),
                ('paraderos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.paraderos')),
                ('rutas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.rutas')),
            ],
        ),
        migrations.CreateModel(
            name='Rutas_PuntosRecargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.buses')),
                ('puntos_recargas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.puntos_recargas')),
                ('rutas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.rutas')),
            ],
        ),
        migrations.DeleteModel(
            name='Puntos_Recarga',
        ),
    ]
