# Generated by Django 5.2.1 on 2025-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portales', '0003_paraderos_remove_portales_puntos_recarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paraderos',
            name='nombre',
            field=models.CharField(default='Paradero desconocido', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portales',
            name='tipo_transporte',
            field=models.CharField(default='Paradero desconocido', max_length=150),
            preserve_default=False,
        ),
    ]
