# Generated by Django 5.2.1 on 2025-06-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portales', '0004_paraderos_nombre_portales_tipo_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='tipo_transporte',
            field=models.CharField(default='Bus desconocido', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paraderos',
            name='tipo_transporte',
            field=models.CharField(default='Paradero desconocido', max_length=150),
            preserve_default=False,
        ),
    ]
