# Generated by Django 5.2.1 on 2025-06-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portales', '0005_buses_tipo_transporte_paraderos_tipo_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='buses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='Portales.buses'),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='programas_Rutas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programas_rutas', to='Portales.programas_rutas'),
        ),
    ]
