# Generated by Django 5.2.1 on 2025-05-31 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Portales', '0003_paraderos_remove_portales_puntos_recarga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(null=True)),
                ('medio', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta_Favorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.IntegerField(default=0)),
                ('saldo_final', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_inicial', models.CharField(max_length=150)),
                ('punto_final', models.CharField(max_length=150)),
                ('rutas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.rutas')),
                ('rutas_buses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portales.buses')),
            ],
        ),
    ]
