# Generated by Django 5.2.1 on 2025-06-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta_favorita',
            name='Punto_Final',
            field=models.CharField(default='Portal Desconocido', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta_favorita',
            name='Punto_Inicial',
            field=models.CharField(default='Portal Americas', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjeta_usuario',
            name='numero_tarjeta',
            field=models.IntegerField(default=0),
        ),
    ]
