# Generated by Django 5.2.1 on 2025-06-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_ruta_favorita_punto_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta_usuario',
            name='saldo_final',
        ),
    ]
